# Generated by Django 4.2.1 on 2023-05-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(db_column='task_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('due_date', models.DateField()),
                ('repeat', models.CharField(verbose_name=2)),
                ('completed', models.SmallIntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.SmallIntegerField()),
            ],
        ),
    ]
